---
version: "3.8"

volumes:
    acme:
        name: acme
        driver: local
        
services:
    traefik:
        command:
            - --accessLog=true
            - --global.sendAnonymousUsage=false
            - --global.checkNewVersion=false
            - --log.level=ERROR
            - --providers.docker=true
            - --providers.docker.swarmMode=false
            - --providers.docker.exposedByDefault=false
            - --providers.docker.network=traefik
            - --providers.docker.watch=true
            - --providers.docker.endpoint=unix:///var/run/docker.sock

            # Let's encrypt HTTP
            - --certificatesResolvers.letsencrypt-http.acme.email=hosting@efsa.io
            - --certificatesResolvers.letsencrypt-http.acme.storage=/etc/traefik/acme/acme.json
            - --certificatesResolvers.letsencrypt-http.acme.httpChallenge.entrypoint=web

            ## Port 80
            - --entrypoints.web.address=:80
            - --entrypoints.web.http.tls=false
            - --entrypoints.web.http.redirections.entrypoint.permanent=true
            - --entrypoints.web.http.redirections.entrypoint.scheme=https
            - --entrypoints.web.http.redirections.entrypoint.to=websecure

            ## Port 443
            - --entrypoints.websecure.address=:443
            - --entrypoints.websecure.http.tls=true
            - --entrypoints.websecure.http.tls.certresolver=letsencrypt-http

            # FTP stuff
            - --entrypoints.ftp21.address=:21
            - --entrypoints.ftp21.http.tls=false
            - --entrypoints.ftp30000.address=:30000
            - --entrypoints.ftp30000.http.tls=false
            - --entrypoints.ftp30001.address=:30001
            - --entrypoints.ftp30001.http.tls=false
            - --entrypoints.ftp30002.address=:30002
            - --entrypoints.ftp30002.http.tls=false
            - --entrypoints.ftp30003.address=:30003
            - --entrypoints.ftp30003.http.tls=false
            - --entrypoints.ftp30004.address=:30004
            - --entrypoints.ftp30004.http.tls=false
            - --entrypoints.ftp30005.address=:30005
            - --entrypoints.ftp30005.http.tls=false
            - --entrypoints.ftp30006.address=:30006
            - --entrypoints.ftp30006.http.tls=false
            - --entrypoints.ftp30007.address=:30007
            - --entrypoints.ftp30007.http.tls=false
            - --entrypoints.ftp30008.address=:30008
            - --entrypoints.ftp30008.http.tls=false
            - --entrypoints.ftp30009.address=:30009
            - --entrypoints.ftp30009.http.tls=false

            ## SSH/SFTP
            - --entrypoints.sftp.address=:2222
            - --entrypoints.sftp.http.tls=false

            ## Dashboard
            - --api.insecure=false
            - --api.dashboard=false
        volumes:
            -   read_only: true
                source: /var/run/docker.sock
                target: /var/run/docker.sock
                type: bind
            -   source: acme
                target: /etc/traefik/acme
                type: volume
        ports:
            -   mode: host
                published: 21
                target: 21
                protocol: tcp
            -   published: 80
                target: 80
                protocol: tcp
                mode: host
            -   published: 443
                target: 443
                protocol: tcp
                mode: host
            -   published: 2222
                target: 2222
                protocol: tcp
                mode: host
            -   mode: host
                published: 30000
                target: 30000
                protocol: tcp
            -   mode: host
                published: 30001
                target: 30001
                protocol: tcp
            -   mode: host
                published: 30002
                target: 30002
                protocol: tcp
            -   mode: host
                published: 30003
                target: 30003
                protocol: tcp
            -   mode: host
                published: 30004
                target: 30004
                protocol: tcp
            -   mode: host
                published: 30005
                target: 30005
                protocol: tcp
            -   mode: host
                published: 30006
                target: 30006
                protocol: tcp
            -   mode: host
                published: 30007
                target: 30007
                protocol: tcp
            -   mode: host
                published: 30008
                target: 30008
                protocol: tcp
            -   mode: host
                published: 30009
                target: 30009
                protocol: tcp
